#!/bin/sh
gitshortref="$(git rev-parse --short HEAD)"
LDB_BACKEND=fs pytest -n0 --benchmark-save fs-"$gitshortref"-local-"$(date -u '+%Y-%m-%d-T-%H-%M-%S-%N')" --benchmark-group-by func tests/benchmarks
LDB_BACKEND=duckdb pytest -n0 --benchmark-save duckdb-"$gitshortref"-local-"$(date -u '+%Y-%m-%d-T-%H-%M-%S-%N')" --benchmark-group-by func tests/benchmarks
LDB_BACKEND=sqlite pytest -n0 --benchmark-save sqlite-"$gitshortref"-local-"$(date -u '+%Y-%m-%d-T-%H-%M-%S-%N')" --benchmark-group-by func tests/benchmarks

pytest-benchmark compare
