name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: venv-cache
        with:
          path: ./venv
          key: ${{ runner.os }}-venv-${{ hashFiles('setup.cfg') }}
      - run: echo cache-hit is ${{ steps.venv-cache.outputs.cache-hit }}
      - name: Install lint dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ./venv
          ./venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install '.[lint]'
      - name: Run linters
        run: |
          ./venv/bin/activate
          SKIP=no-commit-to-branch pre-commit run -a --show-diff-on-failure
